services:

  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./litellm/init-litellm-db.sql:/docker-entrypoint-initdb.d/init-litellm-db.sql
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-telepace}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-app}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@telepace.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-telepace}
      - PGADMIN_CONFIG_SERVER_MODE=True
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.${STACK_NAME:-nexus}-pgadmin-http.rule=Host(`pgadmin.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME:-nexus}-pgadmin-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME:-nexus}-pgadmin-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME:-nexus}-pgadmin-https.rule=Host(`pgadmin.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME:-nexus}-pgadmin-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME:-nexus}-pgadmin-https.tls=true
      - traefik.http.routers.${STACK_NAME:-nexus}-pgadmin-https.tls.certresolver=le
      - traefik.http.services.${STACK_NAME:-nexus}-pgadmin.loadbalancer.server.port=80

  prestart:
    image: '${DOCKER_IMAGE_BACKEND:-telepace/nexus-backend}:${TAG:-latest}'
    build:
      context: ./backend
    networks:
      - traefik-public
      - default
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: bash scripts/prestart.sh
    volumes:
      - ./backend/app/alembic:/app/app/alembic
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN:-localhost.nip.io}
      - FRONTEND_HOST=${FRONTEND_HOST:-http://localhost:3000}
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-http://localhost,http://localhost:3000,https://localhost,https://localhost:3000,http://localhost.nip.io}
      - SECRET_KEY=${SECRET_KEY:-changeme}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER:-admin@telepace.com}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD:-telepace}
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_USER=${SMTP_USER:-telepace}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-telepace}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL:-noreply@yourdomain.com}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-telepace}
      - SENTRY_DSN=${SENTRY_DSN:-}

  backend:
    image: '${DOCKER_IMAGE_BACKEND:-telepace/nexus-backend}:${TAG:-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      db:
        condition: service_healthy
        restart: true
      prestart:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN:-localhost.nip.io}
      - FRONTEND_HOST=${FRONTEND_HOST:-http://localhost:3000}
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-http://localhost,http://localhost:3000,https://localhost,https://localhost:3000,http://localhost.nip.io}
      - SECRET_KEY=${SECRET_KEY:-changeme}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER:-admin@telepace.com}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD:-telepace}
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_USER=${SMTP_USER:-telepace}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-telepace}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL:-noreply@yourdomain.com}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-telepace}
      - SENTRY_DSN=${SENTRY_DSN:-}
      - SUPABASE_URL=${SUPABASE_URL:-}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5

    build:
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME:-nexus}-backend.loadbalancer.server.port=${BACKEND_CONTAINER_PORT:-8000}

      - traefik.http.routers.${STACK_NAME:-nexus}-backend-http.rule=Host(`api.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME:-nexus}-backend-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME:-nexus}-backend-https.rule=Host(`api.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME:-nexus}-backend-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME:-nexus}-backend-https.tls=true
      - traefik.http.routers.${STACK_NAME:-nexus}-backend-https.tls.certresolver=le

      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.${STACK_NAME:-nexus}-backend-http.middlewares=https-redirect

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND:-telepace/nexus-frontend}:${TAG:-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://api.${DOMAIN:-localhost.nip.io}
        - NODE_ENV=${NODE_ENV:-production}
    environment:
      - VITE_API_URL=${PRODUCTION_API_URL:-https://api.${DOMAIN:-localhost.nip.io}}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME:-nexus}-frontend.loadbalancer.server.port=${FRONTEND_CONTAINER_PORT:-3000}

      - traefik.http.routers.${STACK_NAME:-nexus}-frontend-http.rule=Host(`dashboard.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME:-nexus}-frontend-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME:-nexus}-frontend-https.rule=Host(`dashboard.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-https.rule=Host(`dashboard.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-https.tls=true
      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-https.tls.certresolver=le

      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.middlewares=https-redirect

  admin:
    image: '${DOCKER_IMAGE_ADMIN:-telepace/nexus-admin}:${TAG:-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    build:
      context: ./admin
      args:
        - VITE_API_URL=https://api.${DOMAIN:-localhost.nip.io}
        - VITE_ADMIN_API_URL=https://api.${DOMAIN:-localhost.nip.io}
        - VITE_DOMAIN=${DOMAIN:-localhost.nip.io}
        - VITE_PROJECT_NAME=${PROJECT_NAME:-nexus}
        - VITE_ENVIRONMENT=${ENVIRONMENT:-local}
        - NODE_ENV=${NODE_ENV:-production}
    environment:
      - VITE_API_URL=${PRODUCTION_API_URL:-https://api.${DOMAIN:-localhost.nip.io}}
      - VITE_ADMIN_API_URL=${PRODUCTION_API_URL:-https://api.${DOMAIN:-localhost.nip.io}}
      - VITE_DOMAIN=${DOMAIN:-localhost.nip.io}
      - VITE_PROJECT_NAME=${PROJECT_NAME:-nexus}
      - VITE_ENVIRONMENT=${ENVIRONMENT:-local}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME:-nexus}-admin.loadbalancer.server.port=${ADMIN_CONTAINER_PORT:-5173}

      - traefik.http.routers.${STACK_NAME:-nexus}-admin-http.rule=Host(`admin.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME:-nexus}-admin-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME:-nexus}-admin-https.rule=Host(`admin.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME:-nexus}-admin-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME:-nexus}-admin-https.tls=true
      - traefik.http.routers.${STACK_NAME:-nexus}-admin-https.tls.certresolver=le

      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.${STACK_NAME:-nexus}-admin-http.middlewares=https-redirect

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - traefik-public
      - default
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    restart: always
    networks:
      - traefik-public
      - default
    volumes:
      - ./litellm/config.yaml:${LITELLM_CONFIG_PATH:-/app/config.yaml}
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:telepace@db/litellm}
      - STORE_MODEL_IN_DB=${LITELLM_STORE_MODEL_IN_DB:-True}
      - LITELLM_PORT=${LITELLM_PORT:-4000}
      - LITELLM_CONFIG_PATH=${LITELLM_CONFIG_PATH:-/app/config.yaml}
      - LITELLM_STORE_MODEL_IN_DB=${LITELLM_STORE_MODEL_IN_DB:-True}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY:-telepace}
      - OR_SITE_URL=${OR_SITE_URL:-https://openrouter.ai/api/v1}
      - OR_APP_NAME=${OR_APP_NAME:-LiteLLM Nexus app}
      - OR_API_KEY=${OR_API_KEY:-sk-or-v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - GITHUB_API_KEY=${GITHUB_API_KEY:-sk}
      - VOLCENGINE_API_KEY=${VOLCENGINE_API_KEY:-sk}
      - VOLCENGINE_BASE_URL=${VOLCENGINE_BASE_URL:-https://api.volcengine.com/v1}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-sk-lf}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-pk-lf}
      - LANGFUSE_HOST=${LANGFUSE_HOST:-https://cloud.langfuse.com}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "http://localhost:${LITELLM_PORT:-4000}/health/liveliness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.services.${STACK_NAME:-nexus}-litellm.loadbalancer.server.port=${LITELLM_PORT:-4000}
      - traefik.http.routers.${STACK_NAME:-nexus}-litellm-http.rule=Host(`llm.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME:-nexus}-litellm-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME:-nexus}-litellm-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME:-nexus}-litellm-https.rule=Host(`llm.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME:-nexus}-litellm-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME:-nexus}-litellm-https.tls=true
      - traefik.http.routers.${STACK_NAME:-nexus}-litellm-https.tls.certresolver=le

  prometheus:
    image: prom/prometheus
    restart: always
    networks:
      - traefik-public
      - default
    volumes:
      - prometheus-data:/prometheus
      - ./litellm/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.services.${STACK_NAME:-nexus}-prometheus.loadbalancer.server.port=9090
      - traefik.http.routers.${STACK_NAME:-nexus}-prometheus-http.rule=Host(`prometheus.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME:-nexus}-prometheus-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME:-nexus}-prometheus-http.middlewares=https-redirect,admin-auth
      - traefik.http.routers.${STACK_NAME:-nexus}-prometheus-https.rule=Host(`prometheus.${DOMAIN:-localhost.nip.io}`)
      - traefik.http.routers.${STACK_NAME:-nexus}-prometheus-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME:-nexus}-prometheus-https.tls=true
      - traefik.http.routers.${STACK_NAME:-nexus}-prometheus-https.tls.certresolver=le
      - traefik.http.routers.${STACK_NAME:-nexus}-prometheus-https.middlewares=admin-auth

volumes:
  app-db-data:
  pgadmin-data:
  prometheus-data:
  redis-data:

networks:
  traefik-public:
    # Allow setting it to false for testing
    external: true
