version: '3.8'

services:
  docs:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME:-user}/nexus-docs:latest
    container_name: nexus-docs
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - quick-forge-network

networks:
  quick-forge-network:
    external: true
    name: ${COMPOSE_PROJECT_NAME:-quick-forge}_default 