global:
  env: production
  domain: quickforge.example.com
  stackName: qforge
  apiUrl: "https://api.quickforge.example.com"
  frontendHost: "https://dashboard.quickforge.example.com"
  imageTag: stable
  imageRepository: telepace
  
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "CHANGE_ME"
    POSTGRES_DB: app
    POSTGRES_PORT: 5432
    POSTGRES_SERVER: postgresql
    
    SECRET_KEY: "CHANGE_ME"
    
    BACKEND_CORS_ORIGINS: '["https://dashboard.quickforge.example.com", "https://api.quickforge.example.com"]'
    
    FIRST_SUPERUSER: admin@example.com
    FIRST_SUPERUSER_PASSWORD: "CHANGE_ME"
    
    SMTP_HOST: "smtp.example.com"
    SMTP_USER: "info@example.com"
    SMTP_PASSWORD: "CHANGE_ME"
    EMAILS_FROM_EMAIL: "info@example.com"
    
    SENTRY_DSN: "CHANGE_ME"

backend:
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  ingress:
    hosts:
      - host: api.quickforge.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: backend-tls
        hosts:
          - api.quickforge.example.com

frontend:
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  ingress:
    hosts:
      - host: dashboard.quickforge.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: frontend-tls
        hosts:
          - dashboard.quickforge.example.com
  
  buildArgs:
    VITE_API_URL: "https://api.quickforge.example.com"
    NODE_ENV: production

website:
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  ingress:
    hosts:
      - host: docs.quickforge.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: website-tls
        hosts:
          - docs.quickforge.example.com

postgresql:
  auth:
    username: postgres
    password: "CHANGE_ME"
    database: app
  primary:
    persistence:
      size: 20Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true 