app = "nexus-backend"
primary_region = "iad" # Change to your preferred region
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  ENVIRONMENT = "production"
  BACKEND_CORS_ORIGINS = "[\"https://dashboard.your-domain.com\", \"https://your-domain.com\"]" # Update with your domains
  FRONTEND_HOST = "https://dashboard.your-domain.com" # Update with your frontend domain

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/api/v1/utils/health-check/"
    protocol = "http"

[deploy]
  release_command = "alembic upgrade head" 