"""create_favorites_table

Revision ID: 0f6fcd8d9278
Revises: e50a02777538
Create Date: 2025-07-27 15:16:22.452514

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0f6fcd8d9278'
down_revision = 'e50a02777538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_content_segments_item_number', 'content_segments', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_content_segments_item_number', 'content_segments', ['content_item_id', 'display_number'])
    # ### end Alembic commands ###
