"""Fix relationship definitions with foreign annotations

Revision ID: 1bd1ca860f4b
Revises: 364fe2ea66d8
Create Date: 2025-05-26 17:34:43.212107

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1bd1ca860f4b'
down_revision = '364fe2ea66d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
