"""add_unique_constraint_to_content_segments

Revision ID: 1c812fbaf86b
Revises: 6c365e9841fa
Create Date: 2025-07-15 11:58:14.802954

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c812fbaf86b'
down_revision = '6c365e9841fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加唯一约束以支持 ON CONFLICT 语法
    op.create_unique_constraint(
        'uq_content_segments_item_number',
        'content_segments',
        ['content_item_id', 'display_number']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除唯一约束
    op.drop_constraint('uq_content_segments_item_number', 'content_segments', type_='unique')
    # ### end Alembic commands ###
