"""add_access_count_to_contentshare

Revision ID: 25e0ac8d39be
Revises: phase3_001
Create Date: 2025-06-20 21:43:11.506709

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '25e0ac8d39be'
down_revision = 'phase3_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_results_content_item_id_key'), 'ai_results', type_='unique')
    op.drop_index(op.f('ix_ai_results_content_analysis_gin'), table_name='ai_results', postgresql_using='gin')
    op.drop_index(op.f('ix_ai_results_difficulty_quality'), table_name='ai_results')
    op.drop_index(op.f('ix_ai_results_key_points_gin'), table_name='ai_results', postgresql_using='gin')
    op.drop_index(op.f('ix_ai_results_labels_gin'), table_name='ai_results', postgresql_using='gin')
    op.drop_index(op.f('ix_ai_results_summary_gin'), table_name='ai_results', postgresql_using='gin')
    op.drop_constraint(op.f('ai_results_content_item_id_fkey'), 'ai_results', type_='foreignkey')
    op.create_foreign_key(None, 'ai_results', 'contentitem', ['content_item_id'], ['id'])
    op.drop_constraint(op.f('fk_aiconversation_content_item_id'), 'aiconversation', type_='foreignkey')
    op.drop_constraint(op.f('fk_aiconversation_user_id'), 'aiconversation', type_='foreignkey')
    op.create_foreign_key(None, 'aiconversation', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'aiconversation', 'contentitem', ['content_item_id'], ['id'])
    op.drop_constraint(op.f('fk_contentasset_content_item_id'), 'contentasset', type_='foreignkey')
    op.create_foreign_key(None, 'contentasset', 'contentitem', ['content_item_id'], ['id'])
    op.drop_index(op.f('ix_contentitem_project_status'), table_name='contentitem')
    op.drop_index(op.f('ix_contentitem_user_status'), table_name='contentitem')
    op.drop_constraint(op.f('fk_contentitem_user_id'), 'contentitem', type_='foreignkey')
    op.create_foreign_key(None, 'contentitem', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'contentitem', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('fk_processingjob_content_item_id'), 'processingjob', type_='foreignkey')
    op.create_foreign_key(None, 'processingjob', 'contentitem', ['content_item_id'], ['id'])
    op.drop_index(op.f('ix_segments_content_item_segment_index'), table_name='segments')
    op.drop_index(op.f('ix_segments_content_item_segment_type'), table_name='segments')
    op.drop_constraint(op.f('segments_content_item_id_fkey'), 'segments', type_='foreignkey')
    op.create_foreign_key(None, 'segments', 'contentitem', ['content_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'segments', type_='foreignkey')
    op.create_foreign_key(op.f('segments_content_item_id_fkey'), 'segments', 'contentitem', ['content_item_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_segments_content_item_segment_type'), 'segments', ['content_item_id', 'segment_type'], unique=False)
    op.create_index(op.f('ix_segments_content_item_segment_index'), 'segments', ['content_item_id', 'segment_index'], unique=False)
    op.drop_constraint(None, 'processingjob', type_='foreignkey')
    op.create_foreign_key(op.f('fk_processingjob_content_item_id'), 'processingjob', 'contentitem', ['content_item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'contentitem', type_='foreignkey')
    op.drop_constraint(None, 'contentitem', type_='foreignkey')
    op.create_foreign_key(op.f('fk_contentitem_user_id'), 'contentitem', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_contentitem_user_status'), 'contentitem', ['user_id', 'processing_status'], unique=False)
    op.create_index(op.f('ix_contentitem_project_status'), 'contentitem', ['project_id', 'processing_status'], unique=False)
    op.drop_constraint(None, 'contentasset', type_='foreignkey')
    op.create_foreign_key(op.f('fk_contentasset_content_item_id'), 'contentasset', 'contentitem', ['content_item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'aiconversation', type_='foreignkey')
    op.drop_constraint(None, 'aiconversation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_aiconversation_user_id'), 'aiconversation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_aiconversation_content_item_id'), 'aiconversation', 'contentitem', ['content_item_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'ai_results', type_='foreignkey')
    op.create_foreign_key(op.f('ai_results_content_item_id_fkey'), 'ai_results', 'contentitem', ['content_item_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_ai_results_summary_gin'), 'ai_results', ['summary'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_ai_results_labels_gin'), 'ai_results', ['labels'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_ai_results_key_points_gin'), 'ai_results', ['key_points'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_ai_results_difficulty_quality'), 'ai_results', ['difficulty_level', 'content_quality_score'], unique=False)
    op.create_index(op.f('ix_ai_results_content_analysis_gin'), 'ai_results', ['content_analysis'], unique=False, postgresql_using='gin')
    op.create_unique_constraint(op.f('ai_results_content_item_id_key'), 'ai_results', ['content_item_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
