"""add_user_settings_table

Revision ID: 2654e53ee6cc
Revises: 0f6fcd8d9278
Create Date: 2025-07-29 13:16:46.725464

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2654e53ee6cc'
down_revision = '0f6fcd8d9278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
