"""add favorites table

Revision ID: 2655935df679
Revises: 23f8ca754cf2
Create Date: 2025-06-21 22:20:56.831480

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2655935df679'
down_revision = '23f8ca754cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if constraint exists before dropping
    connection = op.get_bind()
    constraint_exists = connection.execute(
        sa.text("SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'ai_results_content_item_id_key' AND table_name = 'ai_results'")
    ).fetchone()
    
    if constraint_exists:
        op.drop_constraint('ai_results_content_item_id_key', 'ai_results', type_='unique')
    
    # Check and drop indexes if they exist
    index_names = [
        'ix_ai_results_content_analysis_gin',
        'ix_ai_results_difficulty_quality',
        'ix_ai_results_key_points_gin',
        'ix_ai_results_labels_gin',
        'ix_ai_results_summary_gin'
    ]
    
    for index_name in index_names:
        index_exists = connection.execute(
            sa.text(f"SELECT 1 FROM pg_indexes WHERE indexname = '{index_name}'")
        ).fetchone()
        
        if index_exists:
            if 'gin' in index_name:
                op.drop_index(index_name, table_name='ai_results', postgresql_using='gin')
            else:
                op.drop_index(index_name, table_name='ai_results')
    
    # Check and drop foreign key constraints if they exist
    fk_constraint_exists = connection.execute(
        sa.text("SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'ai_results_content_item_id_fkey' AND table_name = 'ai_results'")
    ).fetchone()
    
    if fk_constraint_exists:
        op.drop_constraint('ai_results_content_item_id_fkey', 'ai_results', type_='foreignkey')
    
    op.create_foreign_key(None, 'ai_results', 'contentitem', ['content_item_id'], ['id'])
    
    # Continue with other constraint operations
    fk_aiconv_content_exists = connection.execute(
        sa.text("SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_aiconversation_content_item_id' AND table_name = 'aiconversation'")
    ).fetchone()
    
    if fk_aiconv_content_exists:
        op.drop_constraint('fk_aiconversation_content_item_id', 'aiconversation', type_='foreignkey')
    
    fk_aiconv_user_exists = connection.execute(
        sa.text("SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_aiconversation_user_id' AND table_name = 'aiconversation'")
    ).fetchone()
    
    if fk_aiconv_user_exists:
        op.drop_constraint('fk_aiconversation_user_id', 'aiconversation', type_='foreignkey')
    
    op.create_foreign_key(None, 'aiconversation', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'aiconversation', 'contentitem', ['content_item_id'], ['id'])
    
    fk_contentasset_exists = connection.execute(
        sa.text("SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_contentasset_content_item_id' AND table_name = 'contentasset'")
    ).fetchone()
    
    if fk_contentasset_exists:
        op.drop_constraint('fk_contentasset_content_item_id', 'contentasset', type_='foreignkey')
    
    op.create_foreign_key(None, 'contentasset', 'contentitem', ['content_item_id'], ['id'])
    
    # Check and drop contentitem indexes if they exist
    contentitem_indexes = [
        'ix_contentitem_project_status',
        'ix_contentitem_user_status'
    ]
    
    for index_name in contentitem_indexes:
        index_exists = connection.execute(
            sa.text(f"SELECT 1 FROM pg_indexes WHERE indexname = '{index_name}'")
        ).fetchone()
        
        if index_exists:
            op.drop_index(index_name, table_name='contentitem')
    
    fk_contentitem_user_exists = connection.execute(
        sa.text("SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_contentitem_user_id' AND table_name = 'contentitem'")
    ).fetchone()
    
    if fk_contentitem_user_exists:
        op.drop_constraint('fk_contentitem_user_id', 'contentitem', type_='foreignkey')
    
    op.create_foreign_key(None, 'contentitem', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'contentitem', 'user', ['user_id'], ['id'])
    
    # Check message_segment_references index
    msg_seg_index_exists = connection.execute(
        sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'ix_message_segment_references_conversation_message'")
    ).fetchone()
    
    if msg_seg_index_exists:
        op.drop_index('ix_message_segment_references_conversation_message', table_name='message_segment_references')
    
    fk_processingjob_exists = connection.execute(
        sa.text("SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_processingjob_content_item_id' AND table_name = 'processingjob'")
    ).fetchone()
    
    if fk_processingjob_exists:
        op.drop_constraint('fk_processingjob_content_item_id', 'processingjob', type_='foreignkey')
    
    # 检查 processingjob 表是否存在，如果存在才创建外键约束
    processingjob_table_exists = connection.execute(
        sa.text("SELECT table_name FROM information_schema.tables WHERE table_name = 'processingjob'")
    ).fetchone()
    
    if processingjob_table_exists:
        op.create_foreign_key(None, 'processingjob', 'contentitem', ['content_item_id'], ['id'])
    
    # Check segments indexes
    segments_indexes = [
        'ix_segments_content_item_segment_index',
        'ix_segments_content_item_segment_type'
    ]
    
    for index_name in segments_indexes:
        index_exists = connection.execute(
            sa.text(f"SELECT 1 FROM pg_indexes WHERE indexname = '{index_name}'")
        ).fetchone()
        
        if index_exists:
            op.drop_index(index_name, table_name='segments')
    
    fk_segments_exists = connection.execute(
        sa.text("SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'segments_content_item_id_fkey' AND table_name = 'segments'")
    ).fetchone()
    
    if fk_segments_exists:
        op.drop_constraint('segments_content_item_id_fkey', 'segments', type_='foreignkey')
    
    op.create_foreign_key(None, 'segments', 'contentitem', ['content_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 获取数据库连接以检查表是否存在
    connection = op.get_bind()
    
    op.drop_constraint(None, 'segments', type_='foreignkey')
    op.create_foreign_key('segments_content_item_id_fkey', 'segments', 'contentitem', ['content_item_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_segments_content_item_segment_type', 'segments', ['content_item_id', 'segment_type'], unique=False)
    op.create_index('ix_segments_content_item_segment_index', 'segments', ['content_item_id', 'segment_index'], unique=False)
    
    # 检查 processingjob 表是否存在，如果存在才进行操作
    processingjob_table_exists = connection.execute(
        sa.text("SELECT table_name FROM information_schema.tables WHERE table_name = 'processingjob'")
    ).fetchone()
    
    if processingjob_table_exists:
        op.drop_constraint(None, 'processingjob', type_='foreignkey')
        op.create_foreign_key('fk_processingjob_content_item_id', 'processingjob', 'contentitem', ['content_item_id'], ['id'], ondelete='CASCADE')
    
    op.create_index('ix_message_segment_references_conversation_message', 'message_segment_references', ['conversation_id', 'message_index'], unique=False)
    op.drop_constraint(None, 'contentitem', type_='foreignkey')
    op.drop_constraint(None, 'contentitem', type_='foreignkey')
    op.create_foreign_key('fk_contentitem_user_id', 'contentitem', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_contentitem_user_status', 'contentitem', ['user_id', 'processing_status'], unique=False)
    op.create_index('ix_contentitem_project_status', 'contentitem', ['project_id', 'processing_status'], unique=False)
    op.drop_constraint(None, 'contentasset', type_='foreignkey')
    op.create_foreign_key('fk_contentasset_content_item_id', 'contentasset', 'contentitem', ['content_item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'aiconversation', type_='foreignkey')
    op.drop_constraint(None, 'aiconversation', type_='foreignkey')
    op.create_foreign_key('fk_aiconversation_user_id', 'aiconversation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_aiconversation_content_item_id', 'aiconversation', 'contentitem', ['content_item_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'ai_results', type_='foreignkey')
    op.create_foreign_key('ai_results_content_item_id_fkey', 'ai_results', 'contentitem', ['content_item_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_ai_results_summary_gin', 'ai_results', ['summary'], unique=False, postgresql_using='gin')
    op.create_index('ix_ai_results_labels_gin', 'ai_results', ['labels'], unique=False, postgresql_using='gin')
    op.create_index('ix_ai_results_key_points_gin', 'ai_results', ['key_points'], unique=False, postgresql_using='gin')
    op.create_index('ix_ai_results_difficulty_quality', 'ai_results', ['difficulty_level', 'content_quality_score'], unique=False)
    op.create_index('ix_ai_results_content_analysis_gin', 'ai_results', ['content_analysis'], unique=False, postgresql_using='gin')
    op.create_unique_constraint('ai_results_content_item_id_key', 'ai_results', ['content_item_id'])
    # ### end Alembic commands ###
