"""Update relationship definitions without foreign keys

Revision ID: 364fe2ea66d8
Revises: 647814e097c3
Create Date: 2025-05-26 17:30:59.909613

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '364fe2ea66d8'
down_revision = '647814e097c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
