"""add_ai_conversations_table

Revision ID: 44f949096831
Revises: b60b78a1e5be
Create Date: 2025-06-19 23:25:17.496922

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '44f949096831'
down_revision = 'b60b78a1e5be'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
