"""Remove foreign key constraints

Revision ID: 647814e097c3
Revises: 3d595f99f9dc
Create Date: 2025-05-26 17:28:36.922746

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '647814e097c3'
down_revision = '3d595f99f9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('aiconversation_content_item_id_fkey', 'aiconversation', type_='foreignkey')
    op.drop_constraint('aiconversation_user_id_fkey', 'aiconversation', type_='foreignkey')
    op.drop_constraint('contentasset_content_item_id_fkey', 'contentasset', type_='foreignkey')
    op.drop_constraint('contentitem_user_id_fkey', 'contentitem', type_='foreignkey')
    op.drop_constraint('processingjob_content_item_id_fkey', 'processingjob', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('processingjob_content_item_id_fkey', 'processingjob', 'contentitem', ['content_item_id'], ['id'])
    op.create_foreign_key('contentitem_user_id_fkey', 'contentitem', 'user', ['user_id'], ['id'])
    op.create_foreign_key('contentasset_content_item_id_fkey', 'contentasset', 'contentitem', ['content_item_id'], ['id'])
    op.create_foreign_key('aiconversation_user_id_fkey', 'aiconversation', 'user', ['user_id'], ['id'])
    op.create_foreign_key('aiconversation_content_item_id_fkey', 'aiconversation', 'contentitem', ['content_item_id'], ['id'])
    # ### end Alembic commands ###
