"""Add content_segments table for fast paragraph lookup

Revision ID: 6c365e9841fa
Revises: add_display_number_001
Create Date: 2025-07-15 11:34:06.829629

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c365e9841fa'
down_revision = 'add_display_number_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_segments',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('display_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['contentitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_segments_item_created', 'content_segments', ['content_item_id', 'created_at'], unique=False)
    op.create_index('idx_segments_item_number', 'content_segments', ['content_item_id', 'display_number'], unique=False)
    op.create_index(op.f('ix_content_segments_content_item_id'), 'content_segments', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_content_segments_display_number'), 'content_segments', ['display_number'], unique=False)
    op.create_index(op.f('ix_content_segments_id'), 'content_segments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_segments_id'), table_name='content_segments')
    op.drop_index(op.f('ix_content_segments_display_number'), table_name='content_segments')
    op.drop_index(op.f('ix_content_segments_content_item_id'), table_name='content_segments')
    op.drop_index('idx_segments_item_number', table_name='content_segments')
    op.drop_index('idx_segments_item_created', table_name='content_segments')
    op.drop_table('content_segments')
    # ### end Alembic commands ###
