"""Add deep research job table

Revision ID: 713b69d73b30
Revises: e3997149198e
Create Date: 2025-06-28 15:32:13.002219

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '713b69d73b30'
down_revision = 'e3997149198e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deep_research_jobs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('markdown_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('breadth', sa.Integer(), nullable=False),
    sa.Column('research_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deep_research_jobs_id'), 'deep_research_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_deep_research_jobs_status'), 'deep_research_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_deep_research_jobs_user_id'), 'deep_research_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deep_research_jobs_user_id'), table_name='deep_research_jobs')
    op.drop_index(op.f('ix_deep_research_jobs_status'), table_name='deep_research_jobs')
    op.drop_index(op.f('ix_deep_research_jobs_id'), table_name='deep_research_jobs')
    op.drop_table('deep_research_jobs')
    # ### end Alembic commands ###
