"""add_content_chunks_table

Revision ID: a5ec0a34da72
Revises: 1bd1ca860f4b
Create Date: 2025-05-26 21:08:48.144574

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a5ec0a34da72'
down_revision = '1bd1ca860f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentchunk',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentchunk_chunk_index'), 'contentchunk', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_contentchunk_chunk_type'), 'contentchunk', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_contentchunk_content_item_id'), 'contentchunk', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_contentchunk_id'), 'contentchunk', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contentchunk_id'), table_name='contentchunk')
    op.drop_index(op.f('ix_contentchunk_content_item_id'), table_name='contentchunk')
    op.drop_index(op.f('ix_contentchunk_chunk_type'), table_name='contentchunk')
    op.drop_index(op.f('ix_contentchunk_chunk_index'), table_name='contentchunk')
    op.drop_table('contentchunk')
    # ### end Alembic commands ###
