"""add enabled field to prompts table

Revision ID: b0c92ff46404
Revises: a5ec0a34da72
Create Date: 2025-05-26 22:35:15.808303

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b0c92ff46404'
down_revision = 'a5ec0a34da72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
