"""Add collected_blocks table

Revision ID: b491d7283c5b
Revises: 1c812fbaf86b
Create Date: 2025-07-17 16:58:02.732856

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b491d7283c5b'
down_revision = '1c812fbaf86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_content_segments_item_number', 'content_segments', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_content_segments_item_number', 'content_segments', ['content_item_id', 'display_number'])
    # ### end Alembic commands ###
