"""add_ai_conversations_table

Revision ID: b60b78a1e5be
Revises: 4f8214eee196
Create Date: 2025-06-19 23:13:06.717101

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b60b78a1e5be'
down_revision = '4f8214eee196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
