"""add unique constraint to favorites

Revision ID: c7fe05ceeab8
Revises: 2655935df679
Create Date: 2025-06-21 22:22:41.452912

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c7fe05ceeab8'
down_revision = '2655935df679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
