"""add_content_shares_table

Revision ID: d833ea6f9420
Revises: 9a6058d599a7
Create Date: 2025-05-31 12:18:45.948247

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes # Ensures SQLModel types are registered for SA
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd833ea6f9420'
down_revision = '9a6058d599a7' # Adjust if necessary based on actual latest migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentshare',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content_item_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('share_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('max_access_count', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['contentitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentshare_share_token'), 'contentshare', ['share_token'], unique=True)
    op.create_index(op.f('ix_contentshare_is_active'), 'contentshare', ['is_active'], unique=False)
    op.create_index(op.f('ix_contentshare_content_item_id'), 'contentshare', ['content_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contentshare_content_item_id'), table_name='contentshare')
    op.drop_index(op.f('ix_contentshare_is_active'), table_name='contentshare')
    op.drop_index(op.f('ix_contentshare_share_token'), table_name='contentshare')
    op.drop_table('contentshare')
    # ### end Alembic commands ###
