"""add_avatar_url_to_user

Revision ID: dd4b00c23094
Revises: 5ee6589f44e3
Create Date: 2025-05-23 18:46:46.254059

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd4b00c23094'
down_revision = '5ee6589f44e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prompt_tags_prompt_id_fkey', 'prompt_tags', type_='foreignkey')
    op.drop_constraint('prompt_tags_tag_id_fkey', 'prompt_tags', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_tags', 'prompts', ['prompt_id'], ['id'])
    op.create_foreign_key(None, 'prompt_tags', 'tags', ['tag_id'], ['id'])
    op.drop_index('ix_prompt_versions_version', table_name='prompt_versions')
    op.drop_constraint('prompt_versions_prompt_id_fkey', 'prompt_versions', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_versions', 'prompts', ['prompt_id'], ['id'])
    op.drop_index('ix_prompts_created_by', table_name='prompts')
    op.drop_index('ix_prompts_type', table_name='prompts')
    op.drop_index('ix_prompts_visibility', table_name='prompts')
    op.add_column('user', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    op.create_index('ix_prompts_visibility', 'prompts', ['visibility'], unique=False)
    op.create_index('ix_prompts_type', 'prompts', ['type'], unique=False)
    op.create_index('ix_prompts_created_by', 'prompts', ['created_by'], unique=False)
    op.drop_constraint(None, 'prompt_versions', type_='foreignkey')
    op.create_foreign_key('prompt_versions_prompt_id_fkey', 'prompt_versions', 'prompts', ['prompt_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_prompt_versions_version', 'prompt_versions', ['version'], unique=False)
    op.drop_constraint(None, 'prompt_tags', type_='foreignkey')
    op.drop_constraint(None, 'prompt_tags', type_='foreignkey')
    op.create_foreign_key('prompt_tags_tag_id_fkey', 'prompt_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('prompt_tags_prompt_id_fkey', 'prompt_tags', 'prompts', ['prompt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
