"""add_optimized_title_and_brief_description_to_ai_results

Revision ID: e3997149198e
Revises: 61f9810aa1b0
Create Date: 2025-06-24 17:15:52.619067

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e3997149198e'
down_revision = '61f9810aa1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_results', sa.Column('optimized_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('ai_results', sa.Column('brief_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_results', 'brief_description')
    op.drop_column('ai_results', 'optimized_title')
    # ### end Alembic commands ###
