"""upgrade_favorites_table_for_block_support

Revision ID: e50a02777538
Revises: 30d0a5c3cac5
Create Date: 2025-07-17 18:18:04.786642

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e50a02777538'
down_revision = '30d0a5c3cac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('favorites', sa.Column('block_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('favorites', sa.Column('block_content', sa.JSON(), nullable=True))
    op.add_column('favorites', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('favorites', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('favorites', sa.Column('tags', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('unique_user_content_favorite'), 'favorites', type_='unique')
    op.create_unique_constraint('unique_user_content_block_favorite', 'favorites', ['user_id', 'content_item_id', 'block_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_content_block_favorite', 'favorites', type_='unique')
    op.create_unique_constraint(op.f('unique_user_content_favorite'), 'favorites', ['user_id', 'content_item_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('favorites', 'tags')
    op.drop_column('favorites', 'description')
    op.drop_column('favorites', 'title')
    op.drop_column('favorites', 'block_content')
    op.drop_column('favorites', 'block_type')
    op.drop_column('favorites', 'block_id')
    # ### end Alembic commands ###
