// This file is auto-generated by @hey-api/openapi-ts

export type ApiResponse_dict_str__Any__ = {
    data: {
        [key: string]: unknown;
    };
    message?: string;
    meta?: ({
    [key: string]: unknown;
} | null);
};

export type ApiResponse_list_dict_str__Any___ = {
    data: Array<{
        [key: string]: unknown;
    }>;
    message?: string;
    meta?: ({
    [key: string]: unknown;
} | null);
};

export type ApiResponse_NoneType_ = {
    data?: (unknown | null);
    meta?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
};

export type ApiResponse_SmartRoutingResponse_ = {
    data: SmartRoutingResponse;
    message?: string;
    meta?: ({
    [key: string]: unknown;
} | null);
};

export type app__schemas__common__ApiResponse_ProjectPublic_ = {
    data: ProjectPublic;
    message?: string;
    meta?: ({
    [key: string]: unknown;
} | null);
};

export type app__schemas__common__ApiResponse_ProjectsPublic_ = {
    data: ProjectsPublic;
    message?: string;
    meta?: ({
    [key: string]: unknown;
} | null);
};

export type app__utils__response__ApiResponse_ProjectPublic_ = {
    data?: (unknown | null);
    meta?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
};

export type app__utils__response__ApiResponse_ProjectsPublic_ = {
    data?: (unknown | null);
    meta?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
};

export type Body_chat_create_chat_completion = {
    /**
     * Chat messages in OpenAI format
     */
    messages: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Model to use
     */
    model?: string;
    /**
     * Whether to stream the response
     */
    stream?: boolean;
    /**
     * Sampling temperature
     */
    temperature?: number;
    /**
     * Maximum tokens to generate
     */
    max_tokens?: number;
};

export type Body_content_analyze_content_ai_sdk = {
    /**
     * Analysis instruction/prompt
     */
    user_prompt: string;
    /**
     * Model to use
     */
    model?: string;
    /**
     * Sampling temperature
     */
    temperature?: number;
    /**
     * Maximum tokens to generate
     */
    max_tokens?: number;
};

export type Body_content_analyze_content_stream = {
    /**
     * System prompt for analysis
     */
    system_prompt: string;
    /**
     * User prompt (content text)
     */
    user_prompt: string;
};

export type Body_content_content_completion_stream = {
    /**
     * Analysis prompt
     */
    prompt: string;
    /**
     * Model to use
     */
    model?: string;
    /**
     * Sampling temperature
     */
    temperature?: number;
    /**
     * Maximum tokens to generate
     */
    max_tokens?: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CompletionRequest = {
    model?: (string | null);
    messages: Array<LLMMessage>;
    temperature?: (number | null);
    max_tokens?: (number | null);
    stream?: (boolean | null);
    top_p?: (number | null);
    stop?: (string | Array<(string)> | null);
    presence_penalty?: (number | null);
    frequency_penalty?: (number | null);
    logit_bias?: ({
    [key: string]: (number);
} | null);
    user?: (string | null);
    metadata?: ({
    [key: string]: (string);
} | null);
    api_key?: (string | null);
};

export type ContentItemCreate = {
    type: string;
    source_uri?: (string | null);
    title?: (string | null);
    summary?: (string | null);
    content_text?: (string | null);
};

export type ContentItemPublic = {
    type: string;
    source_uri?: (string | null);
    title?: (string | null);
    summary?: (string | null);
    id: string;
    user_id: string;
    processing_status: string;
    content_text?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ContentShareCreate = {
    expires_at?: (string | null);
    max_access_count?: (number | null);
    password?: (string | null);
};

export type ContentSharePublic = {
    id: string;
    share_token: string;
    created_at: string;
    expires_at?: (string | null);
    is_active: boolean;
};

export type EmbeddingData = {
    object: string;
    embedding: Array<(number)>;
    index: number;
};

export type EmbeddingRequest = {
    input: (string | Array<(string)>);
    model: string;
    user?: (string | null);
    api_key?: (string | null);
};

export type EmbeddingResponse = {
    object: string;
    data: Array<EmbeddingData>;
    model: string;
    usage: EmbeddingUsage;
};

export type EmbeddingUsage = {
    prompt_tokens: number;
    total_tokens: number;
};

export type GoogleCallbackRequest = {
    token: string;
    user_info: {
        [key: string]: unknown;
    };
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ImageCreate = {
    source_url?: (string | null);
    s3_key?: (string | null);
    type?: (string | null);
    size?: (number | null);
    format?: (string | null);
    alt_text?: (string | null);
    importance?: (string | null);
    is_accessible?: (boolean | null);
};

export type ImageResponse = {
    source_url?: (string | null);
    s3_key?: (string | null);
    type?: (string | null);
    size?: (number | null);
    format?: (string | null);
    alt_text?: (string | null);
    importance?: (string | null);
    is_accessible?: (boolean | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    last_checked?: (string | null);
};

export type InputVariable = {
    name: string;
    description?: (string | null);
    required?: boolean;
};

export type LLMMessage = {
    role: string;
    content: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PresignedURLRequest = {
    filename: string;
    content_type: string;
};

export type PresignedURLResponse = {
    presigned_url: string;
    s3_key: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * 创建项目的请求模型
 */
export type ProjectCreate = {
    title: string;
    description?: (string | null);
    project_type?: string;
    is_active?: boolean;
    ai_context?: {
        [key: string]: unknown;
    };
};

/**
 * 公开的项目信息
 */
export type ProjectPublic = {
    title: string;
    description?: (string | null);
    project_type?: string;
    is_active?: boolean;
    ai_context?: {
        [key: string]: unknown;
    };
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * 项目列表响应模型
 */
export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

/**
 * 更新项目的请求模型
 */
export type ProjectUpdate = {
    title?: (string | null);
    description?: (string | null);
    project_type?: (string | null);
    is_active?: (boolean | null);
    ai_context?: ({
    [key: string]: unknown;
} | null);
};

export type Prompt = {
    name: string;
    description?: (string | null);
    content: string;
    type: PromptType;
    input_vars?: (Array<InputVariable> | null);
    visibility: Visibility;
    meta_data?: ({
    [key: string]: unknown;
} | null);
    version?: number;
    /**
     * 是否启用该提示词
     */
    enabled?: boolean;
    team_id?: (string | null);
    id?: string;
    created_at?: string;
    updated_at?: string;
    embedding?: (Array<(number)> | null);
    created_by: string;
};

export type PromptCreate = {
    name: string;
    description?: (string | null);
    content: string;
    type: PromptType;
    input_vars?: (Array<InputVariable> | null);
    visibility: Visibility;
    meta_data?: ({
    [key: string]: unknown;
} | null);
    version?: number;
    /**
     * 是否启用该提示词
     */
    enabled?: boolean;
    team_id?: (string | null);
    tag_ids?: (Array<(string)> | null);
};

export type PromptReadWithTags = {
    name: string;
    description?: (string | null);
    content: string;
    type: PromptType;
    input_vars?: (Array<InputVariable> | null);
    visibility: Visibility;
    meta_data?: ({
    [key: string]: unknown;
} | null);
    version?: number;
    /**
     * 是否启用该提示词
     */
    enabled?: boolean;
    team_id?: (string | null);
    id: string;
    created_by: string;
    created_at: string;
    updated_at: string;
    embedding?: (Array<(number)> | null);
    tags?: Array<Tag>;
};

export type PromptType = 'simple' | 'chat' | 'template' | 'system' | 'function';

export type PromptUpdate = {
    name?: (string | null);
    description?: (string | null);
    content?: (string | null);
    type?: (PromptType | null);
    input_vars?: (Array<InputVariable> | null);
    visibility?: (Visibility | null);
    team_id?: (string | null);
    meta_data?: ({
    [key: string]: unknown;
} | null);
    enabled?: (boolean | null);
    tag_ids?: (Array<(string)> | null);
};

export type PromptVersion = {
    id?: string;
    prompt_id: string;
    version: number;
    content: string;
    input_vars?: (Array<InputVariable> | null);
    created_by: string;
    created_at?: string;
    change_notes?: (string | null);
};

export type PromptVersionCreate = {
    content: string;
    input_vars?: (Array<InputVariable> | null);
    change_notes?: (string | null);
};

/**
 * 智能路由请求模型
 */
export type SmartRoutingRequest = {
    query_text: string;
    context?: ({
    [key: string]: unknown;
} | null);
};

/**
 * 智能路由响应模型
 */
export type SmartRoutingResponse = {
    recommended_project_id?: (string | null);
    recommended_project_name?: (string | null);
    confidence_score: number;
    reasoning: string;
    alternative_projects?: Array<{
        [key: string]: unknown;
    }>;
    should_create_new?: boolean;
    suggested_project_name?: (string | null);
};

export type Tag = {
    id?: string;
    name: string;
    description?: (string | null);
    color?: (string | null);
    created_at?: string;
};

export type TagCreate = {
    name: string;
    description?: (string | null);
    color?: (string | null);
};

export type TagUpdate = {
    name?: (string | null);
    description?: (string | null);
    color?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email?: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    avatar_url?: (string | null);
    is_setup_complete?: boolean;
    password: string;
};

export type UserPublic = {
    email?: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    avatar_url?: (string | null);
    is_setup_complete?: boolean;
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    avatar_url?: (string | null);
    is_setup_complete?: boolean;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    is_setup_complete?: (boolean | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type Visibility = 'public' | 'private' | 'team';

export type ChatCreateChatCompletionData = {
    requestBody: Body_chat_create_chat_completion;
};

export type ChatCreateChatCompletionResponse = (unknown);

export type ChatListAvailableModelsResponse = (unknown);

export type ContentContentEventsEndpointResponse = (unknown);

export type ContentCreateContentItemEndpointData = {
    requestBody: ContentItemCreate;
};

export type ContentCreateContentItemEndpointResponse = (ContentItemPublic);

export type ContentProcessContentItemEndpointData = {
    id: string;
};

export type ContentProcessContentItemEndpointResponse = (ContentItemPublic);

export type ContentListContentItemsEndpointData = {
    /**
     * Maximum number of items to return.
     */
    limit?: number;
    /**
     * Number of items to skip for pagination.
     */
    skip?: number;
};

export type ContentListContentItemsEndpointResponse = (Array<ContentItemPublic>);

export type ContentGetContentItemEndpointData = {
    id: string;
};

export type ContentGetContentItemEndpointResponse = (ContentItemPublic);

export type ContentGetContentMarkdownEndpointData = {
    id: string;
};

export type ContentGetContentMarkdownEndpointResponse = ({
    [key: string]: unknown;
});

export type ContentGetSupportedProcessorsResponse = (unknown);

export type ContentGetContentChunksEndpointData = {
    id: string;
    /**
     * Page number (1-based)
     */
    page?: number;
    /**
     * Number of chunks per page
     */
    size?: number;
};

export type ContentGetContentChunksEndpointResponse = ({
    [key: string]: unknown;
});

export type ContentGetContentChunksSummaryEndpointData = {
    id: string;
};

export type ContentGetContentChunksSummaryEndpointResponse = ({
    [key: string]: unknown;
});

export type ContentAnalyzeContentStreamData = {
    contentId: string;
    requestBody: Body_content_analyze_content_stream;
};

export type ContentAnalyzeContentStreamResponse = (unknown);

export type ContentAnalyzeContentAiSdkData = {
    contentId: string;
    requestBody: Body_content_analyze_content_ai_sdk;
};

export type ContentAnalyzeContentAiSdkResponse = (unknown);

export type ContentContentCompletionStreamData = {
    contentId: string;
    requestBody: Body_content_content_completion_stream;
};

export type ContentContentCompletionStreamResponse = (unknown);

export type ContentCreateShareLinkEndpointData = {
    /**
     * ID of the content item to share
     */
    id: string;
    requestBody: ContentShareCreate;
};

export type ContentCreateShareLinkEndpointResponse = (ContentSharePublic);

export type ContentDeactivateShareLinkEndpointData = {
    /**
     * ID of the content item whose shares to deactivate
     */
    id: string;
};

export type ContentDeactivateShareLinkEndpointResponse = (void);

export type ContentGetSharedContentEndpointData = {
    /**
     * Password for protected content
     */
    password?: (string | null);
    /**
     * The unique share token
     */
    token: string;
};

export type ContentGetSharedContentEndpointResponse = (ContentItemPublic);

export type DashboardAnalyzeQueryData = {
    requestBody: SmartRoutingRequest;
};

export type DashboardAnalyzeQueryResponse = (ApiResponse_SmartRoutingResponse_);

export type DashboardGetDashboardMetricsResponse = (ApiResponse_dict_str__Any__);

export type DashboardGetRecentActivitiesData = {
    limit?: number;
};

export type DashboardGetRecentActivitiesResponse = (ApiResponse_list_dict_str__Any___);

export type DashboardConfirmRoutingData = {
    confirmed: boolean;
    routeId: string;
};

export type DashboardConfirmRoutingResponse = (unknown);

export type DashboardCreateProjectData = {
    requestBody: ProjectCreate;
};

export type DashboardCreateProjectResponse = (app__schemas__common__ApiResponse_ProjectPublic_);

export type DashboardGetUserProjectsData = {
    includeInactive?: boolean;
    limit?: number;
    skip?: number;
};

export type DashboardGetUserProjectsResponse = (app__schemas__common__ApiResponse_ProjectsPublic_);

export type GoogleOauthGoogleCallbackApiData = {
    requestBody: GoogleCallbackRequest;
};

export type GoogleOauthGoogleCallbackApiResponse = (unknown);

export type GoogleOauthGoogleLoginData = {
    extensionCallback?: (string | null);
};

export type GoogleOauthGoogleLoginResponse = (unknown);

export type GoogleOauthGoogleCallbackData = {
    code?: (string | null);
    error?: (string | null);
    state?: (string | null);
};

export type GoogleOauthGoogleCallbackResponse = (unknown);

export type HealthGetHealthApiResponse = (unknown);

export type ImagesGetUploadUrlData = {
    requestBody: PresignedURLRequest;
};

export type ImagesGetUploadUrlResponse = (PresignedURLResponse);

export type ImagesCreateImageRecordData = {
    requestBody: ImageCreate;
};

export type ImagesCreateImageRecordResponse = (ImageResponse);

export type ImagesListImagesData = {
    limit?: number;
    skip?: number;
};

export type ImagesListImagesResponse = (Array<ImageResponse>);

export type ImagesReadImageData = {
    imageId: string;
};

export type ImagesReadImageResponse = (ImageResponse);

export type ImagesDeleteImageData = {
    imageId: string;
};

export type ImagesDeleteImageResponse = (ImageResponse);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (app__utils__response__ApiResponse_ProjectsPublic_);

export type ItemsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ItemsCreateProjectResponse = (app__utils__response__ApiResponse_ProjectPublic_);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (app__utils__response__ApiResponse_ProjectPublic_);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ProjectUpdate;
};

export type ItemsUpdateItemResponse = (app__utils__response__ApiResponse_ProjectPublic_);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (ApiResponse_NoneType_);

export type LlmCreateCompletionData = {
    requestBody: CompletionRequest;
};

export type LlmCreateCompletionResponse = (unknown);

export type LlmCreateEmbeddingData = {
    requestBody: EmbeddingRequest;
};

export type LlmCreateEmbeddingResponse = (EmbeddingResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginLoginAccessTokenHeadResponse = ({
    [key: string]: unknown;
});

export type LoginTestTokenResponse = (UserPublic);

export type LoginLogoutResponse = (Message);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PromptsReadTagsData = {
    limit?: number;
    skip?: number;
};

export type PromptsReadTagsResponse = (Array<Tag>);

export type PromptsCreateTagData = {
    requestBody: TagCreate;
};

export type PromptsCreateTagResponse = (Tag);

export type PromptsUpdateTagData = {
    requestBody: TagUpdate;
    tagId: string;
};

export type PromptsUpdateTagResponse = (Tag);

export type PromptsDeleteTagData = {
    tagId: string;
};

export type PromptsDeleteTagResponse = (void);

export type PromptsCreatePromptData = {
    requestBody: PromptCreate;
};

export type PromptsCreatePromptResponse = (PromptReadWithTags);

export type PromptsReadPromptsData = {
    limit?: number;
    order?: string;
    search?: (string | null);
    skip?: number;
    sort?: (string | null);
    tagIds?: (Array<(string)> | null);
};

export type PromptsReadPromptsResponse = (Array<Prompt>);

export type PromptsReadPromptData = {
    promptId: string;
};

export type PromptsReadPromptResponse = (PromptReadWithTags);

export type PromptsUpdatePromptData = {
    createVersion?: boolean;
    promptId: string;
    requestBody: PromptUpdate;
};

export type PromptsUpdatePromptResponse = (PromptReadWithTags);

export type PromptsDeletePromptData = {
    promptId: string;
};

export type PromptsDeletePromptResponse = (void);

export type PromptsReadPromptVersionsData = {
    promptId: string;
};

export type PromptsReadPromptVersionsResponse = (Array<PromptVersion>);

export type PromptsCreatePromptVersionData = {
    promptId: string;
    requestBody: PromptVersionCreate;
};

export type PromptsCreatePromptVersionResponse = (PromptVersion);

export type PromptsReadPromptVersionData = {
    promptId: string;
    versionNum: number;
};

export type PromptsReadPromptVersionResponse = (PromptVersion);

export type PromptsDuplicatePromptData = {
    promptId: string;
};

export type PromptsDuplicatePromptResponse = (Prompt);

export type PromptsTogglePromptEnabledData = {
    promptId: string;
};

export type PromptsTogglePromptEnabledResponse = (PromptReadWithTags);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersReadUserMeHeadResponse = ({
    [key: string]: unknown;
});

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);