app = "quick-forge-ai-website"
primary_region = "iad" # Change to your preferred region
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000" # Match the exposed port in Dockerfile

[http_service]
  internal_port = 3000 # Match the exposed port in Dockerfile
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 200

  [[http_service.checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/"
    protocol = "http" 