name: Use Make All Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      
      # 分别安装各个目录的依赖
      - name: Install frontend dependencies
        run: pnpm install --dir frontend
        if: hashFiles('frontend/package.json') != ''
      
      - name: Install admin dependencies
        run: pnpm install --dir admin
        if: hashFiles('admin/package.json') != ''
      
      - name: Install extension dependencies
        run: pnpm install --dir extension
        if: hashFiles('extension/package.json') != ''
        
      - name: Make all
        run: make all